name = "clayday"
pages_build_output_dir = "public"
compatibility_date = "2025-01-01"

# After `wrangler d1 create clayday`, paste the printed database_id below.
[[d1_databases]]
binding = "DB"
database_name = "clayday"
database_id = "83bbd2e9-d21a-4b41-bdf8-8d394771e094"
